Automate environment 'reset' process.
bcgov/von-bc-registries-agent-configurations pull request #12
Opened 2019-12-04 21:00 UTC by WadeBarnes

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

2019-12-05 01:03 UTC, esune requested changes

2019-12-05 01:03 UTC, esune commented on openshift/manage
> +    unset local quite
Typo `quite`->`quiet` (it appears to be consistent throughout the file)

2019-12-11 20:25 UTC, WadeBarnes commented on openshift/manage
> +    unset local quite
Fixed

2019-12-12 16:56 UTC, esune approved these changes

2019-12-12 16:56 UTC, merged